Учебный проект: холст
htmlacademy-javascript/74261-code-and-magick-21 pull request #2
Opened 2020-10-06 21:14 UTC by ummlaut

2020-10-07 05:10 UTC, maxim-usikov requested changes

2020-10-07 05:10 UTC, maxim-usikov commented on js/stat.js
> +    const barHeight = BAR_HEIGHT_MAX / getMaxTime(times) * times[j];
нахождение максимального времени лучше вынести из цикла, нам достаточно 1 раз найти максимальное время, а не на каждой итерации

2020-10-07 05:10 UTC, maxim-usikov commented on js/stat.js
> +  ctx.fillStyle = `#000`;
эту строку давай перенесем внутрь функции renderTexts

2020-10-07 05:10 UTC, maxim-usikov commented on js/stat.js
> +  ctx.font = `${Font.SIZE} ${Font.FAMILY}`;
эти 2 строки так же лучше перенести в renderTexts, в renderCloud оставляем только рендер прямоугольников в заданных координатах и цвет

2020-10-07 05:10 UTC, maxim-usikov commented on js/stat.js
> +  }
Стоит переписать функцию, что бы она отображала переданный текст по координатам и цвет.

`const renderText = function(ctx, x, y, text, color) { ... } `

2020-10-07 05:10 UTC, maxim-usikov commented on js/stat.js
> +    ctx.restore();
отрисовку столбца давай вынесем в отдельную функцию.

2020-10-07 19:12 UTC, ummlaut commented
Про нахождение максимального времени не очень понял, там в указанном вами
куске кода я рассчитываю высоту столбца для каждого игрока (в цикле).
Конкретно нахождение максимального времени объявлено выше вне цикла и вне
этой функции и называется getMaxTime. Что именно надо исправить?

ср, 7 окт. 2020 г. в 08:10, Maxim Usikov <notifications@github.com>:

> *@maxim-usikov* requested changes on this pull request.
> ------------------------------
>
> In .eslintignore
> <https://github.com/htmlacademy-javascript/74261-code-and-magick-21/pull/2#discussion_r500732931>
> :
>
> > @@ -1,2 +1 @@
>  webpack.config.js
> -js/game.js
>
> Зачем удалил? Нам не нужно проверять этот файл линтером, поэтому он должен
> быть в .eslintignore
> ------------------------------
>
> In js/stat.js
> <https://github.com/htmlacademy-javascript/74261-code-and-magick-21/pull/2#discussion_r500733620>
> :
>
> > +const CLOUD_HEIGHT = 270;
> +const CLOUD_X = 100;
> +const CLOUD_Y = 10;
> +const GAP = 10;
> +const BAR_WIDTH = 40;
> +const BAR_HEIGHT_MAX = 150;
> +const BAR_GAP = 50;
> +const FONT_GAP = 30;
> +const TEXT_X = 150;
> +
> +const Font = {
> +  SIZE: `16px`,
> +  FAMILY: `PT Mono`,
> +};
> +
> +let getRandom = function (number) {
>
> следует использовать const, вместо let в этом случае. В переменную
> присваиваем функцию и дальше нигде не меняем эту переменную, только
> вызываем функцию.
> ------------------------------
>
> In js/stat.js
> <https://github.com/htmlacademy-javascript/74261-code-and-magick-21/pull/2#discussion_r500737369>
> :
>
> > +  for (let i = 0; i < strings.length; i++) {
> +    ctx.fillText(strings[i], TEXT_X, FONT_GAP * (i + 1));
> +  }
>
> Вместо цикла можем использовать метод массива.
>
> strings.forEach((string, i) => {
>   ctx.fillText(string, TEXT_X, FONT_GAP * (i + 1));});
>
> см.
> https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
>
> PS переписывать с ипользованием метода не обязательно.
> ------------------------------
>
> In js/stat.js
> <https://github.com/htmlacademy-javascript/74261-code-and-magick-21/pull/2#discussion_r500738416>
> :
>
> > +      CLOUD_X + GAP,
> +      CLOUD_Y + GAP,
> +      `rgba(0, 0, 0, 0.3)`
> +  );
> +  renderCloud(
> +      ctx,
> +      CLOUD_X,
> +      CLOUD_Y,
> +      `#fff`
> +  );
> +  renderTexts(ctx, [`Ура вы победили!`, `Список результатов:`]);
> +  ctx.fillStyle = `#000`;
> +
> +  for (let j = 0; j < players.length; j++) {
> +    const colorBar = (players[j] !== `Вы`) ? `hsl(240, ${getRandom(100)}%, 30%)` : `rgba(255, 0, 0, 1)`;
> +    const barHeight = BAR_HEIGHT_MAX / getMaxTime(times) * times[j];
>
> нахождение максимального времени лучше вынести из цикла, нам достаточно 1
> раз найти максимальное время, а не на каждой итерации
> ------------------------------
>
> In js/stat.js
> <https://github.com/htmlacademy-javascript/74261-code-and-magick-21/pull/2#discussion_r500738713>
> :
>
> > +
> +window.renderStatistics = function (ctx, players, times) {
> +  renderCloud(
> +      ctx,
> +      CLOUD_X + GAP,
> +      CLOUD_Y + GAP,
> +      `rgba(0, 0, 0, 0.3)`
> +  );
> +  renderCloud(
> +      ctx,
> +      CLOUD_X,
> +      CLOUD_Y,
> +      `#fff`
> +  );
> +  renderTexts(ctx, [`Ура вы победили!`, `Список результатов:`]);
> +  ctx.fillStyle = `#000`;
>
> эту строку давай перенесем внутрь функции renderTexts
> ------------------------------
>
> In js/stat.js
> <https://github.com/htmlacademy-javascript/74261-code-and-magick-21/pull/2#discussion_r500739987>
> :
>
> > +  ctx.fillStyle = `#111`;
> +  ctx.font = `${Font.SIZE} ${Font.FAMILY}`;
>
> эти 2 строки так же лучше перенести в renderTexts, в renderCloud оставляем
> только рендер прямоугольников в заданных координатах и цвет
> ------------------------------
>
> In js/stat.js
> <https://github.com/htmlacademy-javascript/74261-code-and-magick-21/pull/2#discussion_r500740926>
> :
>
> > +      `#fff`
> +  );
> +  renderTexts(ctx, [`Ура вы победили!`, `Список результатов:`]);
> +  ctx.fillStyle = `#000`;
> +
> +  for (let j = 0; j < players.length; j++) {
> +    const colorBar = (players[j] !== `Вы`) ? `hsl(240, ${getRandom(100)}%, 30%)` : `rgba(255, 0, 0, 1)`;
> +    const barHeight = BAR_HEIGHT_MAX / getMaxTime(times) * times[j];
> +    const playerBarX = CLOUD_X + BAR_GAP + (BAR_GAP + BAR_WIDTH) * j;
> +
> +    ctx.save();
> +    ctx.fillText(players[j], playerBarX, CLOUD_HEIGHT);
> +    ctx.fillText(Math.round(parseInt(times[j], 10)), playerBarX, CLOUD_HEIGHT - barHeight - FONT_GAP);
> +    ctx.fillStyle = colorBar;
> +    ctx.fillRect(playerBarX, BAR_HEIGHT_MAX + CLOUD_X, BAR_WIDTH, -barHeight);
> +    ctx.restore();
>
> отрисовку столбца давай вынесем в отдельную функцию.
> ------------------------------
>
> In js/stat.js
> <https://github.com/htmlacademy-javascript/74261-code-and-magick-21/pull/2#discussion_r500735514>
> :
>
> > +const CLOUD_HEIGHT = 270;
> +const CLOUD_X = 100;
> +const CLOUD_Y = 10;
> +const GAP = 10;
> +const BAR_WIDTH = 40;
> +const BAR_HEIGHT_MAX = 150;
> +const BAR_GAP = 50;
> +const FONT_GAP = 30;
> +const TEXT_X = 150;
> +
> +const Font = {
> +  SIZE: `16px`,
> +  FAMILY: `PT Mono`,
> +};
> +
> +let getRandom = function (number) {
>
> Назовем функцию getRandomInteger, аргумент функции переименуем в max -
> функция возвращает целое число в пределе: [0, 100) (минимальное 0,
> максимальное 99)
> ------------------------------
>
> In js/stat.js
> <https://github.com/htmlacademy-javascript/74261-code-and-magick-21/pull/2#discussion_r500740354>
> :
>
> > +  for (let i = 0; i < strings.length; i++) {
> +    ctx.fillText(strings[i], TEXT_X, FONT_GAP * (i + 1));
> +  }
>
> Стоит переписать функцию, что бы она отображала переданный текст по
> координатам и цвет.
>
> const renderText = function(ctx, x, y, text, color) { ... }
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/htmlacademy-javascript/74261-code-and-magick-21/pull/2#pullrequestreview-503519179>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACO7YRCEJZCY53H7IQG2XC3SJPZ6DANCNFSM4SGR3GOA>
> .
>

2020-10-08 13:59 UTC, maxim-usikov commented
> Про нахождение максимального времени не очень понял, там в указанном вами куске кода я рассчитываю высоту столбца для каждого игрока (в цикле). Конкретно нахождение максимального времени объявлено выше вне цикла и вне этой функции и называется getMaxTime. Что именно надо исправить? ср, 7 окт. 2020 г. в 08:10, Maxim Usikov <notifications@github.com>:
> […](#)

Надо вынести вызов `getMaxTime(times)` из тела цикла. Нет нужды на каждой итерации определять максимальное время, массив `times` не меняется. Нам достаточно 1 раз до цикла определить максимальное время и потом использовать это значение в теле цикла при расчетах.

2020-10-12 18:56 UTC, maxim-usikov requested changes

2020-10-12 18:56 UTC, maxim-usikov commented on js/stat.js
> +let TEXT_Y;
Выносить переменные в верхнюю область видимости не стоит. Если они используются в одной конкретной функции лучше внутри функции и оставь. Иначе у тебя получаются функции с "сайд-эффектом" - такие функции тяжело отлаживать.

2020-10-15 15:17 UTC, maxim-usikov approved these changes

2020-10-15 15:17 UTC, merged