Учебный проект: нас орда
htmlacademy-javascript/74261-code-and-magick-21 pull request #3
Opened 2020-10-19 05:05 UTC by ummlaut

2020-10-19 05:07 UTC, ummlaut commented
генерируется один и тот же персонаж 4 раза, а не 4 разных. Подозреваю, что ошибся в генерации рандомного числа, но может и нет

2020-10-19 18:24 UTC, maxim-usikov requested changes

2020-10-19 18:24 UTC, maxim-usikov commented on js/setup.js
> +};
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/random

2020-10-19 18:24 UTC, maxim-usikov commented on js/setup.js
> +};
Генерацию волшебника перенеси внутрь цикла на 50 строке.

На каждой итерации генерируем волшебника и добавляем его в массив

2020-10-19 18:24 UTC, maxim-usikov commented on js/setup.js
> +const renderWizardsArray = function () {
функцию переименуем давай в createWizardsArray

2020-10-23 08:07 UTC, maxim-usikov approved these changes

2020-10-23 08:07 UTC, merged